frase = input('Digite uma frase: ').strip().lower()
busca = input('Digite a letra para pesquisa: ').lower()
lista = frase.split()
print(lista)
print('Sua frase tem: ', frase.count('a'), 'letras', (busca))
print(f'A letra {busca} aparece pela primeira vez na posição: ', frase.find('a')+1)
print(f'A letra {busca} aparece pela ultima vez na posição: ', frase.rfind('a')+1)
print('A primeira palavra é ', lista[0])
print('A ultima palavra é ', lista[-1])